### ISSUE TITLE
Ability to disable nesting only or dragging only, data-nestable-disabled attribute functionality

### ISSUE THREAD

**Issue by evromalarkey** [Mobius1/NestableJS#1]
Hello,

I am wondering if it would be possible to add parameter to select what to disable. 

Example data-nestable-disabled="nesting" would disable nesting new items into it, but you could still drag the item itself wherever you want. And data-nestable-disabled="dragging" would disable dragging, but you could still nest items into it.

Also, really great work on the lib. Finally great jquery free nestable alternative :)

**Comment by Mobius1** [comment]
Implemented in [`v0.2.0`](https://github.com/Mobius1/NestableJS/releases/tag/0.2.0)

Reopen if needed.
