### ISSUE TITLE
Return more info from stop event

### ISSUE THREAD

**Issue by evromalarkey** [Mobius1/NestableJS#3]
Currently the stop event only returns array of the tree. But it would be great if the event returned also info about what was moved and where. Eg. like in jqtree https://mbraak.github.io/jqTree/#event-tree-move

This is also better for sending new tree state with ajax to server.

**Comment by t0byman** [comment]
I want this too!

**Comment by Mobius1** [comment]
Implemented in [`v0.2.0`](https://github.com/Mobius1/NestableJS/releases/tag/0.2.0)

Reopen if needed.
